import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './common/header/Header';
import Footer from './common/footer/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const classes = `${inter.className} flex flex-col h-screen text-slate-700`;

  return (
    <html lang="en">
      <body className={classes}>
        <Header />
        <main className='bg-slate-50 grow p-5 h-4/6 overflow-auto'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
